### ISSUE TITLE
[Request] Add mod to Thunderstore

### ISSUE THREAD

**Issue by spannerman79** [Pfhoenix/ModConfigEnforcer#1]
As a linux user, to use mods with Valheim (and as Valheim **is** also native on linux) we use r2modman.

That hooks into and uses Thunderstore.

https://valheim.thunderstore.io/package/create/docs/

**Comment by rakleed** [comment]
@Pfhoenix could you please take a look?

**Comment by Pfhoenix** [comment]
When the mod developer experience of Thunderstore.io matches NexusMods.com in functionality and ease of use, I'll consider moving. Until then, I won't.

**Comment by spannerman79** [comment]
You state ease of use - how so?  Thunderstore.io file structure is pretty clear and simple - hell its the same for both mod and modpacks and I actually have a modpack on thunderstore for valheim.

I do know that devs even use Github actions to directly publish to thunderstore (it uses https://valheim.thunderstore.io/api/docs/ ).  So I am not sure what you mean by functionality and ease of use.....
